import { SupportKnowledgeRecord } from './database/supportTypes.ts';

export const DEFAULT_KNOWLEDGE_BASE: SupportKnowledgeRecord[] = [
  {
    id: 'kb_checkin_01',
    question: 'What are the check-in and check-out times?',
    answer: 'Standard check-in is from 14:00 (2:00 PM) and check-out is until 11:00 AM. Flexible early check-in or late checkout can be accommodated complimentary whenever villa availability permits.',
    category: 'Check-in',
    language: 'en',
    status: 'PUBLISHED',
    source: 'FAQ_IMPORT',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'kb_transfer_01',
    question: 'How does the airport transfer work and how far is it?',
    answer: 'Zanzirangi House is located in Kizimkazi Dimbani, approximately 55 minutes from Abeid Amani Karume International Airport (ZNZ). We provide private luxury VIP chauffeur transfers with refreshing cold towels and tropical refreshments upon arrival.',
    category: 'Airport Transfer',
    language: 'en',
    status: 'PUBLISHED',
    source: 'FAQ_IMPORT',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'kb_wifi_01',
    question: 'Is there high-speed Wi-Fi available across the property?',
    answer: 'Yes! High-speed Starlink satellite Wi-Fi (150+ Mbps) is complimentary across all private villas, lush gardens, swimming pools, and dining pavilions, ensuring seamless connectivity for streaming or remote work.',
    category: 'Wi-Fi',
    language: 'en',
    status: 'PUBLISHED',
    source: 'FAQ_IMPORT',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'kb_dining_01',
    question: 'Is breakfast included and what dining options are available?',
    answer: 'A gourmet tropical breakfast is included daily with your stay. Our oceanfront restaurant serves freshly landed Menai Bay seafood, authentic Swahili spice recipes, and international fine dining. In-villa dining is available around the clock.',
    category: 'Dining',
    language: 'en',
    status: 'PUBLISHED',
    source: 'FAQ_IMPORT',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'kb_beach_dining_01',
    question: 'Can we arrange a private romantic dinner on the beach?',
    answer: 'Yes! We arrange unforgettable candlelight dinners directly on the soft white sands or elevated coral terraces with torchlight and a custom 5-course seafood tasting menu.',
    category: 'Dining',
    language: 'en',
    status: 'PUBLISHED',
    source: 'FAQ_IMPORT',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'kb_villas_01',
    question: 'Do all villas have private plunge pools and beach access?',
    answer: 'Every single one of our 8 luxury sanctuaries features its own private freshwater infinity plunge pool, sun loungers, outdoor stone showers, and direct private pathway access to the shores of the Indian Ocean.',
    category: 'Villa',
    language: 'en',
    status: 'PUBLISHED',
    source: 'FAQ_IMPORT',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'kb_safari_01',
    question: 'How can we arrange a Serengeti fly-in safari expedition?',
    answer: 'We organize chartered fly-in safaris directly from Zanzibar airport (approx. 1h 45m) to Serengeti National Park, Ngorongoro Crater, and Tarangire with luxury partner tented camps overlooking migration corridors.',
    category: 'Safari',
    language: 'en',
    status: 'PUBLISHED',
    source: 'FAQ_IMPORT',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'kb_dolphins_01',
    question: 'Can we swim with dolphins in Kizimkazi?',
    answer: 'Kizimkazi is world-renowned for resident pods of wild bottlenose and spinner dolphins in the Menai Bay Conservation Area. We arrange ethical sunrise boat departures with licensed marine conservation guides right from our shore.',
    category: 'Other',
    language: 'en',
    status: 'PUBLISHED',
    source: 'FAQ_IMPORT',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'kb_dhow_01',
    question: 'How do we book a private sunset dhow sailing experience?',
    answer: 'A private wooden dhow sailing experience is unforgettable. Glide across the turquoise Indian Ocean while enjoying chilled Champagne and fresh Swahili canapés as the sun dips below the horizon.',
    category: 'Other',
    language: 'en',
    status: 'PUBLISHED',
    source: 'FAQ_IMPORT',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'kb_spa_01',
    question: 'What spa treatments and massage therapies are offered?',
    answer: 'Our in-villa holistic wellness treatments feature cold-pressed Zanzibari coconut oils, clove and cinnamon body scrubs, and soothing deep-tissue massages performed on your private oceanfront sun deck.',
    category: 'Wellness',
    language: 'en',
    status: 'PUBLISHED',
    source: 'FAQ_IMPORT',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'kb_stonetown_01',
    question: 'Can you organize a guided Stone Town and spice plantation tour?',
    answer: 'We organize private cultural journeys with master Swahili historians through UNESCO-listed Stone Town, followed by a sensory walk through an organic spice plantation tasting fresh vanilla, nutmeg, and cloves.',
    category: 'Other',
    language: 'en',
    status: 'PUBLISHED',
    source: 'FAQ_IMPORT',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'kb_family_01',
    question: 'Is Zanzirangi House suitable for families with children?',
    answer: 'Families are warmly welcomed. We offer interconnecting villa sanctuaries, extra rollaway beds, tailored kids menus, and professional babysitting upon request.',
    category: 'Family',
    language: 'en',
    status: 'PUBLISHED',
    source: 'FAQ_IMPORT',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'kb_honeymoon_01',
    question: 'What special amenities are available for honeymoon couples?',
    answer: 'For honeymooners, we prepare complimentary chilled Champagne, fresh tropical floral arrangements, an intimate sunset dhow cruise, and a romantic beach dinner under the stars.',
    category: 'Villa',
    language: 'en',
    status: 'PUBLISHED',
    source: 'FAQ_IMPORT',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'kb_payment_01',
    question: 'What payment methods and cancellation policies apply?',
    answer: 'We accept major credit cards (Visa, MasterCard, Amex), international bank wire transfers, and mobile payments. Flexible cancellation terms apply up to 14 days prior to arrival with full refund.',
    category: 'Pricing',
    language: 'en',
    status: 'PUBLISHED',
    source: 'FAQ_IMPORT',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'kb_diving_01',
    question: 'Where are the best snorkeling and diving spots nearby?',
    answer: 'Partnering with certified PADI dive masters, we take you to the pristine coral reefs of Mnemba Atoll and Kizimkazi reef to observe sea turtles, manta rays, and vibrant marine life.',
    category: 'Other',
    language: 'en',
    status: 'PUBLISHED',
    source: 'FAQ_IMPORT',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];
